// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    /** This function gets a number(let's call it N) and generates a random using Math.random N times
		 * then, the function calculates the ratio between results that are less than or equal to 0.5 to results 
		 * that are greater than 0.5 */

		int n = Integer.parseInt(args[0]);
		int equalOrlessThanHalf = 0;
		int greaterThanHalf = 0;

		for (int i = 0; i < n; i++) {
			double randNumb = Math.random();
			if (randNumb <= 0.5) {
				equalOrlessThanHalf ++;
			} else {
				greaterThanHalf ++;
			} 
		}
		System.out.println("> 0.5: " + greaterThanHalf + " times");
		System.out.println("<= 0.5: " + equalOrlessThanHalf + " times");
		if (equalOrlessThanHalf > 0 && greaterThanHalf > 0){
			double ratio = (greaterThanHalf > equalOrlessThanHalf) ?
				(double) equalOrlessThanHalf / greaterThanHalf: (double) greaterThanHalf / equalOrlessThanHalf;
			System.out.println("Ratio: "+ ratio);
		}
	}
}
